name: 🚀 Update LoveTakesFlight2023.com
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy code to LoveTakesFlight2023
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Upload changed files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server-dir: ${{ secrets.DIRECTORY }}
